# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-29 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190814_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='added_by_user',
            field=models.CharField(default=b'Cacher', max_length=30),
        ),
    ]
