# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
