# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-30 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20191030_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
