# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-31 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20191030_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='admin_choice',
            field=models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], default=b'No', max_length=3),
        ),
    ]
