# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-31 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_admin_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='admin_choice',
            field=models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], default=b'N', max_length=3),
        ),
    ]
